import { randomInt } from 'node:crypto'
import type { WorkItem } from './types.js'

const blockedRanges: Array<[number, number]> = [
  [ipToInt('0.0.0.0'), ipToInt('0.255.255.255')],
  [ipToInt('10.0.0.0'), ipToInt('10.255.255.255')],
  [ipToInt('100.64.0.0'), ipToInt('100.127.255.255')],
  [ipToInt('127.0.0.0'), ipToInt('127.255.255.255')],
  [ipToInt('169.254.0.0'), ipToInt('169.254.255.255')],
  [ipToInt('172.16.0.0'), ipToInt('172.31.255.255')],
  [ipToInt('192.0.0.0'), ipToInt('192.0.0.255')],
  [ipToInt('192.0.2.0'), ipToInt('192.0.2.255')],
  [ipToInt('192.88.99.0'), ipToInt('192.88.99.255')],
  [ipToInt('192.168.0.0'), ipToInt('192.168.255.255')],
  [ipToInt('198.18.0.0'), ipToInt('198.19.255.255')],
  [ipToInt('198.51.100.0'), ipToInt('198.51.100.255')],
  [ipToInt('203.0.113.0'), ipToInt('203.0.113.255')],
  [ipToInt('224.0.0.0'), ipToInt('239.255.255.255')],
  [ipToInt('240.0.0.0'), ipToInt('255.255.255.255')],
]

export function buildRandomIpv4WorkItems(options: {
  count: number
  profile?: string
  withAssets?: boolean
}): WorkItem[] {
  const profile = options.profile || 'quick'
  const generated = new Set<string>()

  while (generated.size < options.count) {
    generated.add(randomPublicIpv4())
  }

  return [...generated].map((ip, index) => ({
    id: `random-ipv4-${ip.replaceAll('.', '-')}`,
    description: 'Random globally routable IPv4 target generated by the dispatcher.',
    targets: [`ip:${ip}`],
    profile,
    withAssets: options.withAssets ?? false,
    priority: options.count - index,
    policy: {
      rateLimit: 'polite',
      respectOptOut: true,
      notes: 'Generated target. Collector operators remain responsible for lawful scanning.',
    },
    labels: ['random', 'public-ipv4'],
  }))
}

export function randomPublicIpv4(): string {
  for (let attempt = 0; attempt < 10_000; attempt += 1) {
    const value = randomInt(1, 0xffffffff)
    if (isAllowedIpv4Int(value)) {
      return intToIp(value)
    }
  }

  throw new Error('failed to generate a public IPv4 address')
}

export function isAllowedIpv4(ip: string): boolean {
  return isAllowedIpv4Int(ipToInt(ip))
}

function isAllowedIpv4Int(value: number): boolean {
  return !blockedRanges.some(([start, end]) => value >= start && value <= end)
}

function ipToInt(ip: string): number {
  const parts = ip.split('.').map(part => Number(part))
  if (parts.length !== 4 || parts.some(part => !Number.isInteger(part) || part < 0 || part > 255)) {
    throw new Error(`invalid IPv4 address: ${ip}`)
  }

  return (((parts[0] ?? 0) << 24) >>> 0) + ((parts[1] ?? 0) << 16) + ((parts[2] ?? 0) << 8) + (parts[3] ?? 0)
}

function intToIp(value: number): string {
  return [
    (value >>> 24) & 255,
    (value >>> 16) & 255,
    (value >>> 8) & 255,
    value & 255,
  ].join('.')
}
